spring.datasource.url=jdbc:mysql://mysql-23970dbc-boppanamaheswari-c44c.i.aivencloud.com:26391/defaultdb?sslMode=REQUIRED

spring.datasource.username=avnadmin

spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8081
